sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - cd justplaybo && npm install && ng build
      - docker build -t justplaybo/front:$TRAVIS_BUILD_NUMBER -t justplaybo/front:latest .
      - docker push justplaybo/front

notifications:
  slack:
    rooms:
      - ingmmo:SW0ahzRuwFIJKKAlQPzGRg0f#prj-justplay
      - ingmmo:SW0ahzRuwFIJKKAlQPzGRg0f#travisbuilds
